#
# This workflow calls the main distribution pipeline from DuckDB to build, test and release extensions
#
name: Extensions (all platforms)
on:
  workflow_call:
#    inputs:
#      override_git_describe:
#        type: string
#      git_ref:
#        type: string
#      skip_tests:
#        type: string
  workflow_dispatch:
#    inputs:
#      override_git_describe:
#        type: string
#      git_ref:
#        type: string
#      skip_tests:
#        type: string
  push:
    branches-ignore:
      - 'main'
      - 'feature'
      - 'v*.*-*'
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Extensions.yml'
  merge_group:
  pull_request:
    types: [opened, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Extensions.yml'

jobs:
  in-tree-extensions:
    name: In-tree Extensions
    uses: ./.github/workflows/_extension_distribution_and_deploy.yml
    with:
      exclude_archs: 'linux_arm64;linux_amd64_musl;osx_amd64;windows_amd64_mingw;wasm_mvp;wasm_eh;'
      artifact_prefix: in-tree-extensions
      extension_config: |
        duckdb_extension_load(autocomplete)
        duckdb_extension_load(core_functions)
        duckdb_extension_load(icu)
        duckdb_extension_load(json)
        duckdb_extension_load(parquet)
        duckdb_extension_load(tpcds)
        duckdb_extension_load(tpch)
        duckdb_extension_load(demo_capi DONT_LINK)
