#
# This workflow is responsible for building all DuckDB extensions
#

name: Extensions (all platforms)
on:
  workflow_call:
    inputs:
      override_git_describe:
        type: string
      git_ref:
        type: string
      skip_tests:
        type: string
    workflow_dispatch:
      inputs:
        override_git_describe:
          description: 'Version tag to override git describe'
          type: string
        git_ref:
          description: 'Git ref'
          type: string
          required: false
          default: ''
# TODO
#        skip_tests:
#          description: 'Pass "true" to skip tests'
#          type: string
#          required: false
#          default: ''

  push:
    branches-ignore:
      - 'main'
      - 'feature'
      - 'v*.*-*'
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Extensions.yml'
      - '!.github/workflows/_extension_distribution.yml'
  merge_group:
  pull_request:
    types: [opened, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Extensions.yml'

concurrency:
  group: extensions-${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}-${{ inputs.override_git_describe }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  # This first step loads the various extension configs from the ~/.github/config directory storing them to drive the build jobs
  load-extension-configs:
    name: Load Extension Configs
    runs-on: ubuntu-latest
    outputs:
      in_tree_extensions: ${{ steps.set-in-tree-extensions.outputs.extension_config }}
      out_of_tree_extensions: ${{ steps.set-out-of-tree-extensions.outputs.extension_config }}
      rust_based_extensions: ${{ steps.set-rust-based-extensions.outputs.extension_config }}
    steps:
      - uses: actions/checkout@v4

      # Load .github/config/in_tree_extensions.cmake into output variable
      - id: set-in-tree-extensions
        run: |
          in_tree_extensions="`cat .github/config/in_tree_extensions.cmake`"
          echo "extension_config<<EOF" >> $GITHUB_OUTPUT
          echo "$in_tree_extensions" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Load .github/config/out_of_tree_extensions.cmake into output variable
      - id: set-out-of-tree-extensions
        run: |
          out_of_tree_extensions="`cat .github/config/out_of_tree_extensions.cmake`"
          echo "extension_config<<EOF" >> $GITHUB_OUTPUT
          echo "$out_of_tree_extensions" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Load .github/config/rust_based_extensions.cmake into output variable
      - id: set-rust-based-extensions
        run: |
          rust_based_extensions="`cat .github/config/rust_based_extensions.cmake`"
          echo "extension_config<<EOF" >> $GITHUB_OUTPUT
          echo "$rust_based_extensions" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  # Build the extensions from .github/config/in_tree_extensions.cmake
  in-tree-extensions:
    name: In-tree Extensions
    needs: load-extension-configs
    uses: ./.github/workflows/_extension_distribution.yml
    with:
      artifact_prefix: in-tree-extensions
      extension_config: ${{ needs.load-extension-configs.outputs.in_tree_extensions }}
      override_tag: ${{ inputs.override_git_describe }}
      duckdb_ref: ${{ inputs.git_ref }}

  # Build the extensions from .github/config/out_of_tree_extensions.cmake
  out-of-tree-extensions:
    name: Out-of-tree Extensions
    needs: load-extension-configs
    uses: ./.github/workflows/_extension_distribution.yml
    with:
      artifact_prefix: out-of-tree-extensions
      extension_config: ${{ needs.load-extension-configs.outputs.out_of_tree_extensions }}
      override_tag: ${{ inputs.override_git_describe }}
      duckdb_ref: ${{ inputs.git_ref }}

  # Build the extensions from .github/config/rust_based_extensions.cmake
  rust-based-extensions:
    name: Rust-based Extensions
    needs: load-extension-configs
    uses: ./.github/workflows/_extension_distribution.yml
    with:
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools;windows_amd64_mingw;linux_amd64_musl'
      artifact_prefix: rust-based-extensions
      extension_config: ${{ needs.load-extension-configs.outputs.rust_based_extensions }}
      extra_toolchains: 'rust'
      override_tag: ${{ inputs.override_git_describe }}
      duckdb_ref: ${{ inputs.git_ref }}

  # Merge all extensions into a single, versioned repository
  create-extension-repository:
    name: Create Extension Repository
    runs-on: ubuntu-latest
    needs:
      - in-tree-extensions
      - out-of-tree-extensions
      - rust-based-extensions
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - uses: actions/download-artifact@v4
        with:
          pattern: in-tree-extensions-${{ github.sha }}*
          path: /tmp/repository_generation/in-tree-extensions

      - uses: actions/download-artifact@v4
        with:
          pattern: out-of-tree-extensions-${{ github.sha }}*
          path: /tmp/repository_generation/out-of-tree-extensions

      - uses: actions/download-artifact@v4
        with:
          pattern: rust-based-extensions-${{ github.sha }}*
          path: /tmp/repository_generation/rust-based-extensions

      - name: Print all extensions
        run: |
          tree /tmp/repository_generation

      - name: Merge into single repository
        run: |
          mkdir /tmp/merged_repository
          cp -r  /tmp/repository_generation/*/*/* /tmp/merged_repository
          tree /tmp/merged_repository

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: extension-repository-${{ github.sha }}
          path: |
            /tmp/merged_repository/**/*.duckdb_extension*

  upload-extensions:
    name: Upload Extensions
    runs-on: ubuntu-latest
    needs:
        - create-extension-repository

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - uses: actions/download-artifact@v4
        with:
          pattern: extension-repository-${{ github.sha }}
          path: /tmp/extension_repository

      - name: List extensions to deploy
        shell: bash
        run: |
          tree /tmp/repository_generation

      - name: Deploy extensions
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.S3_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.S3_KEY}}
#          DUCKDB_DEPLOY_SCRIPT_MODE: for_real TODO: restore
          DUCKDB_EXTENSION_SIGNING_PK: ${{ secrets.DUCKDB_EXTENSION_SIGNING_PK }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          pip install awscli
          ./scripts/extension-upload-repository.sh /tmp/repository_generation

# TODO: add jobs that depend on extensions to be built here