#
# This workflow is responsible for building all DuckDB ext
#

name: Extensions (all platforms)
on:
  workflow_call:
#    inputs:
#      override_git_describe:
#        type: string
#      git_ref:
#        type: string
#      skip_tests:
#        type: string
  workflow_dispatch:
#    inputs:
#      override_git_describe:
#        type: string
#      git_ref:
#        type: string
#      skip_tests:
#        type: string
  push:
    branches-ignore:
      - 'main'
      - 'feature'
      - 'v*.*-*'
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Extensions.yml'
      - '!.github/workflows/_extension_distribution.yml'
  merge_group:
  pull_request:
    types: [opened, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Extensions.yml'

jobs:
  # This first step loads the various extension configs from the ~/.github/config directory storing them to drive the build jobs
  load-extension-configs:
    name: Load Extension Configs
    runs-on: ubuntu-latest
    outputs:
      in_tree_extensions: ${{ steps.set-in-tree-extensions.outputs.extension_config }}
      out_of_tree_extensions: ${{ steps.set-out-of-tree-extensions.outputs.extension_config }}
    steps:
      - uses: actions/checkout@v4

      # TODO: this removes newlines?
      - id: set-in-tree-extensions
        run: |
          in_tree_extensions="`cat .github/config/in_tree_extensions.cmake`"
          echo "extension_config<<EOF" >> $GITHUB_OUTPUT
          echo "$in_tree_extensions" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - id: set-out-of-tree-extensions
        run: |
          out_of_tree_extensions="`cat .github/config/out_of_tree_extensions.cmake`"
          echo "extension_config<<EOF" >> $GITHUB_OUTPUT
          echo "$out_of_tree_extensions" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  # This job builds the extension from .github/config/in_tree_extensions.cmake
  in-tree-extensions:
    name: In-tree Extensions
    needs: load-extension-configs
    uses: ./.github/workflows/_extension_distribution.yml
    with:
      exclude_archs: 'linux_arm64;linux_amd64;linux_amd64_musl;osx_amd64;windows_amd64_mingw;wasm_mvp;wasm_eh;windows_amd64'
      artifact_prefix: in-tree-extensions
      extension_config: ${{ needs.load-extension-configs.outputs.in_tree_extensions }}

  # This job builds the extension from .github/config/out_of_tree_extensions.cmake
  out-of-tree-extensions:
    name: Out-of-tree Extensions
    needs: load-extension-configs
    uses: ./.github/workflows/_extension_distribution.yml
    with:
      exclude_archs: 'linux_arm64;linux_amd64;linux_amd64_musl;osx_amd64;windows_amd64_mingw;wasm_mvp;wasm_eh;windows_amd64'
      artifact_prefix: out-of-tree-extensions
      extension_config: ${{ needs.load-extension-configs.outputs.out_of_tree_extensions }}

  # Merge all extensions into a single, versioned repository
  create-extension-repository:
    name: Create Extension Repository
    runs-on: ubuntu-latest
    needs:
      - in-tree-extensions
      - out-of-tree-extensions
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - uses: actions/download-artifact@v4
        with:
          pattern: in-tree-extensions-${{ github.sha }}*
          path: /tmp/repository_generation/in-tree-extensions-1

      - uses: actions/download-artifact@v4
        with:
          pattern: out-of-tree-extensions-${{ github.sha }}*
          path: /tmp/repository_generation/in-tree-extensions-2

      - name: Print all extensions
        run: |
          tree /tmp/repository_generation

      - name: Merge into single repository
        run: |
          mkdir /tmp/merged_repository
          cp -r  /tmp/repository_generation/*/*/* /tmp/merged_repository
          tree /tmp/merged_repository

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: extension-repository-${{ github.sha }}
          path: |
            /tmp/merged_repository/**/*.duckdb_extension*