name: Main
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches-ignore:
      - 'main'
      - 'feature'
      - 'v*.*-*'
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Main.yml'
      - '.github/config/extensions/*.cmake'
      - '.github/patches/extensions/**/*.patch'
      - '!.github/patches/extensions/fts/*.patch' # fts used in some jobs
      - '!.github/config/extensions/fts.cmake'
  merge_group:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft]
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Main.yml'
      - '.github/config/extensions/*.cmake'
      - '.github/patches/extensions/**/*.patch'
      - '!.github/patches/extensions/fts/*.patch' # fts used in some jobs
      - '!.github/config/extensions/fts.cmake'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
 # TODO: Bring back BLOCK_VERIFICATION: 1, and consider bringing back fts
 # TODO: DEBUG_STACKTRACE: 1 + reldebug ?
 linux-configs:
    name: Tests a release build with different configurations
    runs-on: ubuntu-24.04
#    needs: check-draft
    env:
      BASE_BRANCH: ${{ github.base_ref || 'main' }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install
      shell: bash
      run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build libcurl4-openssl-dev

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ vars.BRANCHES_TO_BE_CACHED == '' || contains(vars.BRANCHES_TO_BE_CACHED, github.ref) }}

    - name: Build
      id: build
      shell: bash
      env:
        CORE_EXTENSIONS: "json;parquet;icu;tpch;tpcds"
        GEN: ninja
      run: make

    - name: test/configs/force_storage.json
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/force_storage.json

    - name: test/configs/force_storage_restart.json
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/force_storage_restart.json

    - name: test/configs/latest_storage.json
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/latest_storage.json

    - name: test/configs/verify_fetch_row.json
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/verify_fetch_row.json

    - name: test/configs/wal_verification.json
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/wal_verification.json

    - name: test/configs/prefetch_all_parquet_files.json
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/prefetch_all_parquet_files.json

    - name: test/configs/no_local_filesystem.json
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/no_local_filesystem.json

    - name: test/configs/block_size_16kB.json
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/block_size_16kB.json

    - name: test/configs/latest_storage_block_size_16kB.json
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/latest_storage_block_size_16kB.json

    - name: test/configs/enable_verification.json
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/enable_verification.json

    - name: Test dictionary_expression
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --verify-vector dictionary_expression --skip-compiled

    - name: Test dictionary_operator
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --verify-vector dictionary_operator --skip-compiled

    - name: Test constant_operator
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --verify-vector constant_operator --skip-compiled

    - name: Test sequence_operator
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --verify-vector sequence_operator --skip-compiled

    - name: Test nested_shuffle
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --verify-vector nested_shuffle --skip-compiled

    - name: Test variant_vector
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/variant_vector.json

    - name: Test variant_vector
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/compressed_in_memory.json

    - name: Forwards compatibility tests
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        python3 scripts/test_storage_compatibility.py --versions "1.2.1|1.3.2" --new-unittest build/release/test/unittest

    # TODO: clean this up: we should probably be able to run this whole test suite with httpfs
    # We want to run the remainder of tests with httpfs
    - name: Build with httpfs extension
      id: build-httpfs
      shell: bash
      if: (success() || failure()) && steps.build.conclusion == 'success'
      env:
        CORE_EXTENSIONS: "json;parquet;icu;tpch;tpcds;httpfs"
        GEN: ninja
      run:
        make

    - name: test/configs/encryption.json
      if: (success() || failure()) && steps.build.conclusion == 'success'
      shell: bash
      run: |
        ./build/release/test/unittest --test-config test/configs/encryption.json
