name: Main CI Pipeline
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - '**'
      - '!master'
      - '!feature'
    tags:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, reopened, ready_for_review]
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  RUN_PYTHON_PIPELINE: 1
  RUN_MAIN_PIPELINE: 1

jobs:
  configure-pipeline:
    name: Configures the pipeline based on which files were modified
    runs-on: ubuntu-latest
    steps:
      - uses: Ana06/get-changed-files@v2.2.0
        with:
          format: 'json'

      - name: Print changed files on which we want to base our pipeline scheduling logic
        shell: bash
        run:
          echo "These are all the changed files in JSON format:"
          echo "${{ steps.files.outputs.all }}"

  linux-release:
    needs: pre-pipeline-job
    if: ${{ env.RUN_MAIN_PIPELINE }}
    uses: ./.github/workflows/LinuxRelease.yml

  python:
    needs: pre-pipeline-job
    if: ${{ env.RUN_PYTHON_PIPELINE }}
    uses: ./.github/workflows/Python.yml

  post-pipeline-job:
    name: Post-check for full pipeline
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    needs: [linux-release, python]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pre pipeline step
        shell: bash
        run:
          echo "RINGALINGADING SHITS DONE";
